version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
Run-With-Node:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          name: install and run tests
          command: |
            yarn install && yarn test
      - codecov/upload:
          file: './coverage/clover.xml'
          token: a7a5df63-codcov-token-4278vh38  
jobs:   
 build:     
  docker:       
   - image: alpine:3.7     
  steps:       
    - checkout       
    - run:           
       name: The First Step           
       command: |             
         echo 'Hello World!'             
         echo 'This is the delivery pipeline'       
    - run:           
        name: Code has arrived           
        command: |             
          ls -al             
          echo '^^^That should look familiar^^^'
