codecov:
  require_ci_to_pass: yes
  branch: main
  
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 0%
        threshold: 100%
    patch:
      default:
        target: 0%
        threshold: 100%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
